# Generated by Django 4.0.3 on 2022-04-21 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='consent',
            field=models.BooleanField(default=False),
        ),
    ]
