# Generated by Django 4.0.3 on 2022-04-07 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_day_remove_schedule_month_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='level',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
