# Generated by Django 4.0.3 on 2022-04-07 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0004_project_documents'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='speciality',
            options={'verbose_name_plural': 'Specialities'},
        ),
    ]
