# Generated by Django 4.0.3 on 2022-04-08 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0005_alter_speciality_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='specialties',
            new_name='specialities',
        ),
    ]
