# Generated by Django 4.0.3 on 2022-04-19 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0007_alter_day_name_alter_project_documents_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='documents',
            field=models.ManyToManyField(blank=True, to='schools.document'),
        ),
        migrations.AlterField(
            model_name='project',
            name='schedules',
            field=models.ManyToManyField(blank=True, to='schools.schedule'),
        ),
        migrations.AlterField(
            model_name='project',
            name='skills',
            field=models.ManyToManyField(blank=True, to='schools.skill'),
        ),
        migrations.AlterField(
            model_name='project',
            name='students',
            field=models.ManyToManyField(blank=True, to='schools.student'),
        ),
        migrations.AlterField(
            model_name='project',
            name='teachers',
            field=models.ManyToManyField(blank=True, to='schools.teacher'),
        ),
        migrations.AlterField(
            model_name='student',
            name='groups',
            field=models.ManyToManyField(blank=True, to='schools.group'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='specialities',
            field=models.ManyToManyField(blank=True, to='schools.speciality'),
        ),
    ]
